steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'

    args:
      - gcloud
      - functions
      - deploy
      - function-gcp
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=java17
      - --entry-point com.example.GCPexamples.HttpMethod